### ISSUE TITLE
Bug with optimization for 3 pods

### ISSUE THREAD

**Issue by makarty** [criticalhop/kalc#135] opened 2020-01-21 20:46 UTC
issue:

**Comment by makarty** [comment] 2020-01-21 20:51
Reproducer: 

kalc: a9a30d88031ea56a8a7f1d10ccccd9c3d3b44991
poodle: ce993ede4004ddbfb6993a2675740b6d58fe016b
launch:POODLE_SOLVER_URL=http://localhost:10442 PYTHON=pypy tox -e poodledev -- -x -s tests/test_cli_optimize.py

Error message: 
================================================== FAILURES ==================================================
___________________________________________ test_optimmize_cluster ___________________________________________

    def test_optimmize_cluster():
        k, p, test_case = prepare_affinity_test_8_pods_on_3_nodes_with_6_antiaffinity_pods()
        yaml_dump = convert_space_to_yaml_dump(k.state_objects)
        # print("Running with", yaml_dump)
>       optimize_cluster(yaml_dump)

tests/test_cli_optimize.py:275: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kalc/misc/cli_optimize.py:110: in optimize_cluster
    problem.xrun()
kalc/misc/problem.py:80: in xrun
    self.run(timeout, sessionName, schedule=xschedule, raise_=True)
kalc/misc/problem.py:69: in run
    sessionName=sessionName
.tox/poodledev/lib/python3.7/site-packages/poodle-0.2.4-py3.7.egg/poodle/schedule.py:228: in xschedule
    return [x() for x in schedule(methods, space, exit, goal, sessionName, timeout)][-1]
.tox/poodledev/lib/python3.7/site-packages/poodle-0.2.4-py3.7.egg/poodle/schedule.py:228: in <listcomp>
    return [x() for x in schedule(methods, space, exit, goal, sessionName, timeout)][-1]
.tox/poodledev/lib/python3.7/site-packages/poodle-0.2.4-py3.7.egg/poodle/poodle_main.py:2256: in __call__
    return self.wrappedMethod[0].__call__(**self.kwargs)
kalc/model/kubeactions.py:434: in MoveRunningPodToAnotherNode
    self.script.append(move_pod_with_deployment_script_simple(pod, nodeTo, self.objectList))
kalc/misc/script_generator.py:35: in move_pod_with_deployment_script_simple
    get_rs_from_deployment(d, object_space))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

deployment = None
object_space = [<kalc.model.system.Scheduler.Scheduler object at 0x7fa8a6c74d50>, <kalc.model.system.globals.GlobalVar object at 0x7f...kalc.model.kinds.Service.Service object at 0x7fa8a6df8790>, <kalc.model.kinds.Node.Node object at 0x7fa8a6d2c150>, ...]

    def get_rs_from_deployment(deployment, object_space):
        replicasets = filter(lambda x: isinstance(x, rs.ReplicaSet), object_space)
        for replicaset in replicasets:
>           if replicaset.metadata_ownerReferences__name == deployment.metadata_name:
E           AttributeError: 'NoneType' object has no attribute 'metadata_name'

kalc/misc/script_generator.py:17: AttributeError
========================================= slowest 100 test durations =========================================
766.50s call     tests/test_cli_optimize.py::test_optimmize_cluster
0.00s setup    tests/test_cli_optimize.py
0.00s teardown tests/test_cli_optimize.py::test_optimmize_cluster
0.00s setup    tests/test_cli_optimize.py::test_optimmize_cluster
0.00s teardown tests/test_cli_optimize.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================ 1 failed, 1 skipped, 1 warning in 767.86s (0:12:47) =============================
ERROR: InvocationError for command /home/vasily/artem/kalc/.tox/poodledev/bin/python -m pytest -vv --durations=100 --disable-pytest-warnings --pylint --pylint-jobs=4 --pylint-error-types=EF -x -s tests/test_cli_optimize.py (exited with code 1)
__________________________________________________ summary ___________________________________________________
ERROR:   poodledev: commands failed

**Comment by grandrew** [comment] 2020-01-21 21:23
Duplicate of #114

**Closed** 2020-01-21 21:24 UTC
Labels: bug, duplicate
